### ISSUE TITLE
Burgers Code error

### ISSUE THREAD

**Issue by luocr7** [neuraloperator/neuraloperator#180] opened 2023-07-19 15:23 UTC
RuntimeError: The size of tensor a (2) must match the size of tensor b (16) at non-singleton dimension 3

**Comment by JeanKossaifi** [comment] 2023-07-19 17:11
Can you please share minimal snippet of code to reproduce your error and make sure you are using the latest version?

**Comment by luocr7** [comment] 2023-07-29 16:24
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate),After I removed the parameter weight_decay, it worked,why?

**Comment by JeanKossaifi** [comment] 2023-08-02 01:12
Could you share a minimal code to reproduce the issue on a dummy model and data?

**Comment by karanprime** [comment] 2023-08-03 14:29
Hello, I faced similar errors after upgrading my Pytorch to 2.0. I spent a few days checking my code but since the error was in the optimizer, it was very frustrating to debug. 

I then created a new environment with the Pytorch version before I upgraded and it all started working. My current working environment has these versions: Python 3.9.6, Pytorch 1.11.0, Cuda 10.2. 

Hope it helps.

@JeanKossaifi It seems new Pytorch versions are breaking the code. Would it be possible to add specific versions in the requirements.txt? I can share the requirements.txt of my last working environment.

**Comment by crwhite14** [comment] 2023-08-03 20:37
This might be because of the known error with complex numbers with torch 2.0.0 and 2.0.1. Myself and others ran into that issue a couple times with other neuraloperator commands, and we got similar error messages. See this thread for the issue and the fix: https://github.com/pytorch/pytorch/pull/100973

It is just a 1-2 line fix to the torch files. Can you check if that fixes it (i.e., doing the change [here](https://github.com/pytorch/pytorch/pull/100973))?

If that is true, it is not an issue with neuraloperator. It is an issue with torch and will be fixed with torch 2.0.2.

**Comment by JeanKossaifi** [comment] 2023-08-08 02:31
@karanprime did this fix your issue?

**Comment by JeanKossaifi** [comment] 2023-10-12 23:31
Closing as resolved

**Closed by JeanKossaifi** 2023-10-12 23:31 UTC
