### ISSUE TITLE
Bayesian Inverse Problems

### ISSUE THREAD

**Issue by zouhang0914** [neuraloperator/neuraloperator#207] opened 2023-08-30 07:07 UTC
Hi, sorry to be a bother.
I want to reproduce the Bayesian inverse problems in "FOURIER NEURAL OPERATOR FOR PARAMETRIC PARTIAL DIFFERENTIAL EQUATIONS".
Could you please provide some related repositories.
thanks!

**Comment by JeanKossaifi** [comment] 2023-10-12 23:28
Closing as duplicate of #227

**Closed by JeanKossaifi** 2023-10-12 23:28 UTC
